import type { College } from "./types";

/**
 * Bangalore college directory — Phase 1.
 *
 * Promotion policy (intentional friction):
 *   1. Run `python scripts/match/colleges_radius.py <slug>` to confirm
 *      ≥ 1 real xerox shop exists within 1.5 km of campus coords.
 *   2. Verify 2–3 of those shops in Google Maps manually.
 *   3. Flip `presence: "live"` and set `verifiedAt: "<today>"`.
 *   4. Swap the (still factual, but branching) intro to a present-tense
 *      version that names the live kiosk tier explicitly.
 *   5. Bump `lastReviewed`. CI runs the verify:pseo gate which fails
 *      if a live college has zero shops in radius.
 *
 * Until promoted, every intro on this page is intentionally
 * "see nearby shops" wording — no claim of a kiosk existing.
 */
const colleges: College[] = [
  // ---------------------------------------------------------------------
  // EXISTING 5 — intros rewritten to remove kiosk-existence claims.
  // ---------------------------------------------------------------------
  {
    slug: "iisc-bangalore",
    name: "Indian Institute of Science",
    shortName: "IISc",
    city: "bengaluru",
    address: "CV Raman Avenue, Bengaluru, Karnataka 560012",
    lat: 13.0219,
    lng: 77.5673,
    intro:
      "IISc students and researchers looking for nearby print shops often need thesis printing, late-night assignments, and last-minute research papers — see verified xerox shops within 1.5 km of the IISc campus.",
    keywords: [
      "print near iisc bangalore",
      "thesis printing near iisc",
      "document print cv raman avenue",
      "assignment print jigni",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "rvce-bengaluru",
    name: "RV College of Engineering",
    shortName: "RVCE",
    city: "bengaluru",
    address: "RV Vidyaniketan Post, Mysore Road, Bengaluru, Karnataka 560059",
    lat: 12.9357,
    lng: 77.5015,
    intro:
      "RVCE students printing project reports, seminar papers, and placement resumes frequently compare xerox shops along Mysore Road — see verified print shops near the RVCE campus.",
    keywords: [
      "print near rvce",
      "project report printing rv college",
      "resume print mysore road",
      "xerox shop mysore road bangalore",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "pes-university-ec-campus",
    name: "PES University (EC Campus)",
    shortName: "PESU EC",
    city: "bengaluru",
    address: "Electronic City, Hosur Road, Bengaluru, Karnataka 560100",
    lat: 12.9139,
    lng: 77.6604,
    intro:
      "PESU students in Electronic City often need assignment print, placement CV print, and lab report print on short notice — see verified xerox shops near PES University's Electronic City campus.",
    keywords: [
      "print near pes university electronic city",
      "resume printing pesu",
      "assignment print electronic city bangalore",
      "xerox shop electronic city",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "christ-university-central-campus",
    name: "Christ University (Central Campus)",
    shortName: "Christ Central",
    city: "bengaluru",
    address: "Dharmaram College Post, Hosur Road, Bengaluru, Karnataka 560029",
    lat: 12.9352,
    lng: 77.6045,
    intro:
      "Christ University students often search for exam-form printing, last-minute CV print for placement drives, and assignment print near campus — see verified xerox shops near Christ University on Hosur Road.",
    keywords: [
      "print near christ university bangalore",
      "exam form printing christ university",
      "cv print hosur road",
      "xerox shop bannimantha",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "nitte-meenakshi-bangalore",
    name: "Nitte Meenakshi Institute of Technology",
    shortName: "NMIT",
    city: "bengaluru",
    address: "Govindpura, Yelahanka, Bengaluru, Karnataka 560064",
    lat: 13.0827,
    lng: 77.5765,
    intro:
      "NMIT students living near Yelahanka often need assignment print, project report print, and document print on the same day — see verified xerox shops near NMIT campus.",
    keywords: [
      "print near nmit yelahanka",
      "assignment printing nmit",
      "xerox shop yelahanka bangalore",
      "document print govindpura",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },

  // ---------------------------------------------------------------------
  // NEW ENTRIES — 10 additional Bangalore colleges.
  // Coords verified against Google Maps campus pin; intros factual,
  // no kiosk-existence claims. `area` field dropped where the
  // existing areas.ts slug did not match — geo radius is the
  // primary match path now.
  // ---------------------------------------------------------------------
  {
    slug: "bms-college-of-engineering",
    name: "BMS College of Engineering",
    shortName: "BMSCE",
    city: "bengaluru",
    address: "Bull Temple Road, Basavanagudi, Bengaluru, Karnataka 560019",
    lat: 12.9416,
    lng: 77.5664,
    intro:
      "BMS College of Engineering students on Bull Temple Road often need project report print, IEEE paper print, and placement CV print — see verified xerox shops near BMSCE campus.",
    keywords: [
      "print near bmsce",
      "bms college project report printing",
      "xerox shop basavanagudi",
      "placement cv print bull temple road",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "ms-ramaiah-institute-of-technology",
    name: "M.S. Ramaiah Institute of Technology",
    shortName: "MSRIT",
    city: "bengaluru",
    address: "MSR Nagar, MSRIT Post, Bengaluru, Karnataka 560054",
    lat: 13.0298,
    lng: 77.5645,
    intro:
      "MSRIT students in MSR Nagar often look for same-day assignment print, lab manual print, and placement CV print — see verified xerox shops near the MSRIT campus.",
    keywords: [
      "print near msrit",
      "ms ramaiah assignment printing",
      "xerox shop msr nagar",
      "lab manual print mathikere",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "jain-university-kanakapura-global-campus",
    name: "Jain (Deemed-to-be University) — Kanakapura Global Campus",
    shortName: "Jain Kanakapura",
    city: "bengaluru",
    address: "Jain Global Campus, Kanakapura Road, Bengaluru, Karnataka 562112",
    lat: 12.7692,
    lng: 77.4333,
    intro:
      "Jain University students on Kanakapura Road often need assignment print, project report print, and conference paper print — see verified xerox shops near the Jain campus.",
    keywords: [
      "print near jain university",
      "jain assignment printing kanakapura",
      "xerox shop kanakapura road",
      "project report print jain global campus",
    ],
    presence: "planned",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "presidency-university-bangalore",
    name: "Presidency University",
    shortName: "Presidency",
    city: "bengaluru",
    address: "Itgalpur, Rajanukunte, Yelahanka, Bengaluru, Karnataka 560064",
    lat: 13.1306,
    lng: 77.5847,
    intro:
      "Presidency University students near Yelahanka frequently need assignment print, exam form print, and placement CV print — see verified xerox shops near the Presidency campus.",
    keywords: [
      "print near presidency university",
      "presidency assignment print yelahanka",
      "xerox shop rajanukunte",
      "exam form print presidency",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "acharya-institute-of-technology",
    name: "Acharya Institute of Technology",
    shortName: "AIT",
    city: "bengaluru",
    address: "Acharya Dr. Sarvepalli Radhakrishnan Road, Soldevanahalli, Bengaluru, Karnataka 560107",
    lat: 13.0658,
    lng: 77.4649,
    intro:
      "Acharya Institute of Technology students near Soldevanahalli often need project report print, assignment print, and placement CV print — see verified xerox shops near the AIT campus.",
    keywords: [
      "print near acharya institute",
      "acharya project report print",
      "xerox shop soldevanahalli",
      "placement cv print acharya",
    ],
    presence: "planned",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "reva-university",
    name: "REVA University",
    shortName: "REVA",
    city: "bengaluru",
    address: "Rukmini Knowledge Park, Kattigenahalli, Yelahanka, Bengaluru, Karnataka 560064",
    lat: 13.1208,
    lng: 77.5723,
    intro:
      "REVA University students at Rukmini Knowledge Park frequently need assignment print, lab report print, and thesis print — see verified xerox shops near the REVA campus.",
    keywords: [
      "print near reva university",
      "reva assignment print yelahanka",
      "xerox shop kattigenahalli",
      "thesis print reva",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "dayananda-sagar-college-of-engineering",
    name: "Dayananda Sagar College of Engineering",
    shortName: "DSCE",
    city: "bengaluru",
    address: "Shavige Malleshwara Hills, Kumaraswamy Layout, Bengaluru, Karnataka 560078",
    lat: 12.9089,
    lng: 77.5638,
    intro:
      "DSCE students in Kumaraswamy Layout often need project report print, placement CV print, and assignment print — see verified xerox shops near the DSCE campus.",
    keywords: [
      "print near dsce",
      "dayananda sagar assignment printing",
      "xerox shop kumaraswamy layout",
      "placement cv print dsce",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "st-josephs-college-of-commerce",
    name: "St. Joseph's College of Commerce",
    shortName: "SJCC",
    city: "bengaluru",
    address: "163 Brigade Road, Bengaluru, Karnataka 560025",
    lat: 12.9684,
    lng: 77.6083,
    intro:
      "St. Joseph's College of Commerce students on Brigade Road frequently need assignment print, internship application print, and resume print — see verified xerox shops near the SJCC campus.",
    keywords: [
      "print near sjcc",
      "st josephs commerce assignment printing",
      "xerox shop brigade road",
      "resume print brigade road",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "st-josephs-college",
    name: "St. Joseph's College",
    shortName: "SJC",
    city: "bengaluru",
    address: "36 Lalbagh Road, Bengaluru, Karnataka 560027",
    lat: 12.9563,
    lng: 77.5841,
    intro:
      "St. Joseph's College students on Lalbagh Road often need assignment print, project paper print, and exam form print — see verified xerox shops near the SJC campus.",
    keywords: [
      "print near sjc bangalore",
      "st josephs college assignment printing",
      "xerox shop lalbagh road",
      "exam form print lalbagh",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "mount-carmel-college",
    name: "Mount Carmel College",
    shortName: "MCC",
    city: "bengaluru",
    address: "58 Palace Road, Vasanth Nagar, Bengaluru, Karnataka 560052",
    lat: 12.9891,
    lng: 77.5921,
    intro:
      "Mount Carmel College students on Palace Road frequently need assignment print, internship application print, and CV print — see verified xerox shops near the MCC campus.",
    keywords: [
      "print near mount carmel college",
      "mcc assignment printing vasanth nagar",
      "xerox shop palace road",
      "cv print palace road",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "jyoti-nivas-college",
    name: "Jyoti Nivas College",
    shortName: "JNC",
    city: "bengaluru",
    address: "8th Block, Koramangala, Bengaluru, Karnataka 560095",
    lat: 12.9354,
    lng: 77.6221,
    intro:
      "Jyoti Nivas College students in Koramangala often need assignment print, project report print, and placement CV print — see verified xerox shops near the JNC campus.",
    keywords: [
      "print near jyoti nivas college",
      "jnc assignment printing koramangala",
      "xerox shop koramangala 8th block",
      "placement cv print jnc",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "vijaya-college",
    name: "Vijaya College",
    shortName: "Vijaya",
    city: "bengaluru",
    address: "Basavanagudi, Bengaluru, Karnataka 560004",
    lat: 12.9408,
    lng: 77.5651,
    intro:
      "Vijaya College students in Basavanagudi frequently need assignment print, exam form print, and project report print — see verified xerox shops near the Vijaya campus.",
    keywords: [
      "print near vijaya college",
      "vijaya college assignment printing",
      "xerox shop basavanagudi",
      "exam form print basavanagudi",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "kristu-jayanti-college",
    name: "Kristu Jayanti College",
    shortName: "KJC",
    city: "bengaluru",
    address: "K. Narayanapura, Kothanur, Bengaluru, Karnataka 560077",
    lat: 13.0543,
    lng: 77.6407,
    intro:
      "Kristu Jayanti College students near Kothanur often need assignment print, project report print, and placement CV print — see verified xerox shops near the KJC campus.",
    keywords: [
      "print near kristu jayanti",
      "kjc assignment printing kothanur",
      "xerox shop k narayanapura",
      "placement cv print kjc",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "east-point-college",
    name: "East Point College of Engineering and Technology",
    shortName: "EPCET",
    city: "bengaluru",
    address: "Bidarahalli, Bengaluru, Karnataka 560049",
    lat: 13.0259,
    lng: 77.7081,
    intro:
      "East Point College students near Bidarahalli frequently need assignment print, lab report print, and project report print — see verified xerox shops near the EPCET campus.",
    keywords: [
      "print near east point college",
      "epcet assignment printing bidarahalli",
      "xerox shop bidarahalli",
      "lab report print east point",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },
  {
    slug: "cmrit-bangalore",
    name: "CMR Institute of Technology",
    shortName: "CMRIT",
    city: "bengaluru",
    address: "Whitefield, Bengaluru, Karnataka 560037",
    lat: 12.9856,
    lng: 77.7366,
    intro:
      "CMRIT students in Whitefield often need assignment print, project report print, and placement CV print — see verified xerox shops near the CMRIT campus.",
    keywords: [
      "print near cmrit",
      "cmr institute assignment printing",
      "xerox shop whitefield",
      "placement cv print cmrit",
    ],
    presence: "live",
    verifiedAt: "2026-08-07",
    lastReviewed: "2026-08-07",
  },

  // ---------------------------------------------------------------------
  // NEW ENTRIES — 22 additional Bangalore colleges (2026-08-08).
  // Coords from gosom/google-maps-scraper docker run against official/
  // secondary-source addresses; each confirmed to have >=1 real xerox
  // shop within 1.5km via scripts/match/colleges_radius.py logic before
  // being added here. Christ/PES/Jain campus splits — siblings of the
  // renamed existing entries above.
  // ---------------------------------------------------------------------
  {
    slug: "christ-university-bannerghatta",
    name: "Christ University (Bannerghatta Road Campus)",
    shortName: "Christ Bannerghatta",
    city: "bengaluru",
    address: "Bannerghatta Road, Hulimavu, Bengaluru, Karnataka 560076",
    lat: 12.8778133,
    lng: 77.5957995,
    intro:
      "Christ University students at the Bannerghatta Road campus often need assignment print, exam form print, and placement CV print — see verified xerox shops near the Hulimavu campus.",
    keywords: [
      "print near christ university bannerghatta road",
      "xerox shop hulimavu",
      "assignment print christ bannerghatta",
      "cv print hulimavu bangalore",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "christ-university-yeshwanthpur",
    name: "Christ University (Yeshwanthpur Campus)",
    shortName: "Christ Yeshwanthpur",
    city: "bengaluru",
    address: "Nagasandra, Tumkur Road, Bengaluru, Karnataka 560073",
    lat: 13.0362625,
    lng: 77.5046094,
    intro:
      "Christ University students at the Yeshwanthpur campus often need assignment print, project report print, and exam form print — see verified xerox shops near the Nagasandra campus.",
    keywords: [
      "print near christ university yeshwanthpur",
      "xerox shop nagasandra",
      "assignment print tumkur road",
      "exam form print christ yeshwanthpur",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "pes-university-rr-campus",
    name: "PES University (RR Campus)",
    shortName: "PESU RR",
    city: "bengaluru",
    address: "100 Feet Ring Road, Banashankari, Bengaluru, Karnataka 560085",
    lat: 12.9350817,
    lng: 77.5360407,
    intro:
      "PES University students at the RR (Ring Road) campus often need assignment print, project report print, and placement CV print — see verified xerox shops near the Banashankari campus.",
    keywords: [
      "print near pes university rr campus",
      "xerox shop banashankari ring road",
      "assignment print pesu rr campus",
      "cv print banashankari",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "pes-university-hn-campus",
    name: "PES University (HN Campus)",
    shortName: "PESU HN",
    city: "bengaluru",
    address: "50 Feet Road, Hanumanthanagar, Bengaluru, Karnataka 560050",
    lat: 12.9415076,
    lng: 77.5538015,
    intro:
      "PES University students at the HN (Hanumanthanagar) campus often need assignment print, project report print, and exam form print — see verified xerox shops near the campus.",
    keywords: [
      "print near pes university hn campus",
      "xerox shop hanumanthanagar",
      "assignment print pesu hn campus",
      "document print 50 feet road banashankari",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "jain-university-jc-road",
    name: "Jain (Deemed-to-be University) — JC Road Campus",
    shortName: "Jain JC Road",
    city: "bengaluru",
    address: "34, 1st Cross, JC Road, Bengaluru, Karnataka 560027",
    lat: 12.961148,
    lng: 77.5853956,
    intro:
      "Jain University students at the JC Road campus often need assignment print, project report print, and exam form print — see verified xerox shops near the campus.",
    keywords: [
      "print near jain university jc road",
      "xerox shop jc road bangalore",
      "assignment print jain jc road campus",
      "document print sudhama nagar",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "jain-university-jayanagar",
    name: "Jain (Deemed-to-be University) — Jayanagar Campus",
    shortName: "Jain Jayanagar",
    city: "bengaluru",
    address: "District Fund Road, Jayanagar 9th Block, Bengaluru, Karnataka 560069",
    lat: 12.9181777,
    lng: 77.5918934,
    intro:
      "Jain University School of Commerce students at the Jayanagar campus often need assignment print, project report print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near jain university jayanagar",
      "xerox shop jayanagar 9th block",
      "assignment print jain jayanagar campus",
      "cv print jayanagar bangalore",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "jain-university-lalbagh-road",
    name: "Jain (Deemed-to-be University) — Lalbagh Road Campus",
    shortName: "Jain Lalbagh",
    city: "bengaluru",
    address: "133 Lalbagh Road, Bengaluru, Karnataka 560027",
    lat: 12.9603204,
    lng: 77.5872078,
    intro:
      "Jain University Center for Management Studies students at the Lalbagh Road campus often need assignment print, case study print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near jain university lalbagh road",
      "xerox shop lalbagh road jain",
      "case study print jain cms",
      "cv print lalbagh road bangalore",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "jain-university-gandhi-nagar",
    name: "Jain (Deemed-to-be University) — Gandhi Nagar Campus",
    shortName: "Jain Gandhi Nagar",
    city: "bengaluru",
    address: "17 Seshadri Road, Gandhi Nagar, Bengaluru, Karnataka 560009",
    lat: 12.9802926,
    lng: 77.5779779,
    intro:
      "Jain University CMS Business School students at the Gandhi Nagar campus often need assignment print, case study print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near jain university gandhi nagar",
      "xerox shop gandhi nagar bangalore",
      "assignment print jain cms business school",
      "cv print seshadri road",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "jain-university-shankarapuram",
    name: "Jain (Deemed-to-be University) — Shankarapuram Campus",
    shortName: "Jain Shankarapuram",
    city: "bengaluru",
    address: "Shankar Mutt Main Road, Shankarapuram, Bengaluru, Karnataka 560004",
    lat: 12.951415,
    lng: 77.5701985,
    intro:
      "Jain University School of Law students at the Shankarapuram campus often need assignment print, moot memo print, and exam form print — see verified xerox shops near the campus.",
    keywords: [
      "print near jain university shankarapuram",
      "xerox shop shankarapuram bangalore",
      "moot memo print jain law school",
      "document print shankar mutt road",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "bit-bangalore",
    name: "Bangalore Institute of Technology",
    shortName: "BIT",
    city: "bengaluru",
    address: "K.R. Road, V.V. Puram, Bengaluru, Karnataka 560004",
    lat: 12.9551694,
    lng: 77.5742917,
    intro:
      "BIT students on K.R. Road often need project report print, IEEE paper print, and placement CV print — see verified xerox shops near the BIT campus.",
    keywords: [
      "print near bit bangalore",
      "xerox shop vv puram",
      "project report print bit college",
      "cv print kr road bangalore",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "jssate-bangalore",
    name: "JSS Academy of Technical Education",
    shortName: "JSSATE",
    city: "bengaluru",
    address: "Uttarahalli-Kengeri Main Road, Srinivaspura, Bengaluru, Karnataka 560060",
    lat: 12.9030297,
    lng: 77.5047442,
    intro:
      "JSSATE students near Srinivaspura often need assignment print, lab manual print, and project report print — see verified xerox shops near the JSSATE campus.",
    keywords: [
      "print near jssate bangalore",
      "xerox shop srinivaspura",
      "assignment print jss academy",
      "lab manual print uttarahalli kengeri road",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "rnsit-bangalore",
    name: "RNS Institute of Technology",
    shortName: "RNSIT",
    city: "bengaluru",
    address: "Uttarahalli-Kengeri Main Road, Channasandra, Bengaluru, Karnataka 560098",
    lat: 12.9020479,
    lng: 77.5178374,
    intro:
      "RNSIT students near Channasandra often need assignment print, project report print, and placement CV print — see verified xerox shops near the RNSIT campus.",
    keywords: [
      "print near rnsit bangalore",
      "xerox shop channasandra",
      "assignment print rns institute",
      "cv print uttarahalli kengeri road",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "sapthagiri-coe-bangalore",
    name: "Sapthagiri College of Engineering",
    shortName: "Sapthagiri CoE",
    city: "bengaluru",
    address: "14/5, Chikkasandra, Hesaraghatta Main Road, Bengaluru, Karnataka 560057",
    lat: 13.0676453,
    lng: 77.5044708,
    intro:
      "Sapthagiri College of Engineering students near Chikkasandra often need assignment print, project report print, and lab manual print — see verified xerox shops near the campus.",
    keywords: [
      "print near sapthagiri college of engineering",
      "xerox shop chikkasandra",
      "assignment print sapthagiri",
      "document print hesaraghatta main road",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "dr-ait-bangalore",
    name: "Dr. Ambedkar Institute of Technology",
    shortName: "Dr. AIT",
    city: "bengaluru",
    address: "Outer Ring Road, Mallathahalli, Bengaluru, Karnataka 560056",
    lat: 12.9636721,
    lng: 77.5060307,
    intro:
      "Dr. AIT students near Mallathahalli often need assignment print, project report print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near dr ait bangalore",
      "xerox shop mallathahalli",
      "assignment print ambedkar institute",
      "cv print outer ring road nagarbhavi",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "gat-bangalore",
    name: "Global Academy of Technology",
    shortName: "GAT",
    city: "bengaluru",
    address: "Ideal Homes Township, Rajarajeshwari Nagar, Bengaluru, Karnataka 560098",
    lat: 12.9236217,
    lng: 77.5274567,
    intro:
      "Global Academy of Technology students in Rajarajeshwari Nagar often need assignment print, project report print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near global academy of technology",
      "xerox shop rajarajeshwari nagar",
      "assignment print gat bangalore",
      "cv print ideal homes township",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "sjbit-bangalore",
    name: "SJB Institute of Technology",
    shortName: "SJBIT",
    city: "bengaluru",
    address: "BGS Health & Education City, Kengeri, Bengaluru, Karnataka 560060",
    lat: 12.9006655,
    lng: 77.4972069,
    intro:
      "SJBIT students at BGS Health & Education City often need assignment print, project report print, and placement CV print — see verified xerox shops near the Kengeri campus.",
    keywords: [
      "print near sjbit bangalore",
      "xerox shop kengeri bgs campus",
      "assignment print sjb institute",
      "cv print kengeri bangalore",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "oxford-coe-bangalore",
    name: "The Oxford College of Engineering",
    shortName: "Oxford CoE",
    city: "bengaluru",
    address: "10th Milestone, Bommanahalli, Hosur Road, Bengaluru, Karnataka 560068",
    lat: 12.9016798,
    lng: 77.6313057,
    intro:
      "Oxford College of Engineering students in Bommanahalli often need assignment print, project report print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near oxford college of engineering",
      "xerox shop bommanahalli",
      "assignment print oxford coe",
      "cv print hosur road bommanahalli",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "bmsit-bangalore",
    name: "BMS Institute of Technology & Management",
    shortName: "BMSIT&M",
    city: "bengaluru",
    address: "Avalahalli, Doddaballapura Main Road, Yelahanka, Bengaluru, Karnataka 560064",
    lat: 13.1341876,
    lng: 77.5693927,
    intro:
      "BMSIT&M students near Yelahanka often need assignment print, project report print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near bmsit bangalore",
      "xerox shop avalahalli yelahanka",
      "assignment print bms institute technology management",
      "cv print doddaballapura main road",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "hkbk-coe-bangalore",
    name: "HKBK College of Engineering",
    shortName: "HKBK",
    city: "bengaluru",
    address: "Nagawara, Bengaluru, Karnataka 560045",
    lat: 13.0375716,
    lng: 77.6197085,
    intro:
      "HKBK College of Engineering students near Nagawara often need assignment print, project report print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near hkbk college of engineering",
      "xerox shop nagawara",
      "assignment print hkbk bangalore",
      "cv print manyata tech park road",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "atria-it-bangalore",
    name: "Atria Institute of Technology",
    shortName: "Atria IT",
    city: "bengaluru",
    address: "Anandnagar, Hebbal, Bengaluru, Karnataka 560024",
    lat: 13.0325175,
    lng: 77.592124,
    intro:
      "Atria Institute of Technology students near Hebbal often need assignment print, project report print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near atria institute of technology",
      "xerox shop hebbal anandnagar",
      "assignment print atria bangalore",
      "cv print hebbal",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "tjohn-it-bangalore",
    name: "T John Institute of Technology",
    shortName: "T John IT",
    city: "bengaluru",
    address: "Gottigere, Bannerghatta Road, Bengaluru, Karnataka 560083",
    lat: 12.8510801,
    lng: 77.5947149,
    intro:
      "T John Institute of Technology students near Gottigere often need assignment print, project report print, and placement CV print — see verified xerox shops near the campus.",
    keywords: [
      "print near t john institute of technology",
      "xerox shop gottigere bannerghatta road",
      "assignment print t john bangalore",
      "cv print gottigere",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
  {
    slug: "bu-central-college",
    name: "Bangalore University (Central College Campus)",
    shortName: "BU Central College",
    city: "bengaluru",
    address: "Kempegowda Road, Bengaluru, Karnataka 560001",
    lat: 12.9748663,
    lng: 77.5829672,
    intro:
      "Bangalore University students at the Central College campus often need assignment print, exam form print, and project report print — see verified xerox shops near the campus.",
    keywords: [
      "print near bangalore university central college",
      "xerox shop central college bangalore",
      "assignment print bu central college",
      "document print kempegowda road",
    ],
    presence: "live",
    verifiedAt: "2026-08-08",
    lastReviewed: "2026-08-08",
  },
];

export default colleges;
