// AUTO-GENERATED by scripts/build-faq-tails-ts.mjs — do not hand-edit.
// Run `node scripts/build-faq-tails-ts.mjs` after editing any .json file
// under content/pseo/faq-tails/. Source of truth is the .json files; this
// file is rebuilt from them.

import type { Faq } from "./faqs";

export const faqTails: Record<string, Faq[]> = {
  "area-electronic-city": [{"q":"Is there a Snaprint kiosk in Electronic City?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. Meanwhile, verified partner print shops in Electronic City handle walk-in printing; email snaprints@sanskritilabs.in for details."}],
  "area-hsr-layout": [{"q":"Is there a Snaprint kiosk in HSR Layout?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. Until then, verified partner print shops in HSR Layout cover walk-in printing today."}],
  "area-indiranagar": [{"q":"Where is the nearest Snaprint kiosk in Indiranagar?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. For now, verified partner print shops in Indiranagar handle walk-in printing."}],
  "area-koramangala": [{"q":"Where is the nearest Snaprint kiosk in Koramangala?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. Meanwhile, verified partner print shops in Koramangala cover walk-in printing; contact snaprints@sanskritilabs.in for updates."}],
  "area-malleswaram": [{"q":"Is there a Snaprint kiosk near Malleswaram?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. For now, 19 verified partner print shops in Malleswaram handle walk-in printing."}],
  "area-shivajinagar": [{"q":"Is there a Snaprint kiosk near Shivajinagar?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. For now, the 14 verified partner print shops in Shivajinagar serve as the walk-in option."}],
  "area-ulsoor": [{"q":"Is there a Snaprint kiosk near Ulsoor?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. For now, the 1 verified partner print shop in Ulsoor is the current walk-in option."}],
  "area-whitefield": [{"q":"Is there a Snaprint kiosk near Whitefield / ITPL?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. Contact snaprints@sanskritilabs.in for updates on the Whitefield / ITPL corridor."}],
  "city-bengaluru": [{"q":"Is there a Snaprint kiosk near my college in Bengaluru?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. Meanwhile, verified partner print shops across the city handle walk-in printing near most colleges."}],
  "college-christ-university-central-campus": [{"q":"Is there a Snaprint kiosk near Christ University?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. For now, verified partner print shops near Christ University on Hosur Road handle walk-in printing."}],
  "college-iisc-bangalore": [{"q":"Is there a Snaprint kiosk near IISc?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru, including near IISc on CV Raman Avenue. Verified partner print shops nearby cover walk-in printing today."}],
  "college-nitte-meenakshi-bangalore": [{"q":"Is there a Snaprint kiosk near NMIT Yelahanka?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. For now, verified partner print shops in the Yelahanka locality handle walk-in printing."}],
  "college-pes-university-ec-campus": [{"q":"Is there a Snaprint kiosk near PES University Electronic City?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. Verified partner print shops in the Electronic City campus area handle walk-in printing today."}],
  "college-rvce-bengaluru": [{"q":"Is there a Snaprint kiosk near RVCE on Mysore Road?","a":"Snaprint kiosks haven't launched yet — the first units are coming to Bengaluru. For now, verified partner print shops near RVCE on Mysore Road handle walk-in printing."}],
};
